Vidhusha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap #this
from blog.sitemaps import PostSitemap #this
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
    'posts': PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns=[
    path('',views.post_list,name="post_list"),
    path('<slug:post>/',views.post_detail,name="post_detail"),
    # path('comment/reply/', views.reply_page, name="reply"),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_tag'),
]

blog/models.py
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
import readtime
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField

# creating model manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

# post model
class Post(models.Model):
    STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    creator = models.CharField(max_length=250,default="Unknown...")
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    image = models.ImageField(upload_to='featured_image/%Y/%m/%d/', blank=True)
    body = RichTextUploadingField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager(help_text="Enter your post tags...")
    # slug = AutoSlugField(populate_from='title')
    
    def get_readtime(self):
      result = readtime.of_text(self.body)
      return result.text

    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    class Meta:
        ordering = ('-publish',)
    
    def __str__(self):
        return self.title
    
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.slug])

    def get_comments(self):
        return self.comments.filter(parent=None).filter(active=True)    

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=50)
    email = models.EmailField()
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    body = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return self.body

    def get_comments(self):
        return Comment.objects.filter(parent=self).filter(active=True)

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
    
    # overriding default form setting and adding bootstrap class
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {'placeholder': 'Enter name','class':'form-control'}
        self.fields['email'].widget.attrs = {'placeholder': 'Enter email', 'class':'form-control'}
        self.fields['body'].widget.attrs = {'placeholder': 'Comment here...', 'class':'form-control', 'rows':'5'}

blog/views.py
from django.db.models import Q
from django.db.models import Count
from taggit.models import Tag
from django.shortcuts import render
from .models import Post, Comment
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm
from django.views.generic import ListView, DetailView



def post_list(request, tag_slug=None):
    posts = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    # search
    query = request.GET.get("q")
    if query:
        posts=Post.published.filter(Q(title__icontains=query) | Q(tags__name__icontains=query)).distinct()

    paginator = Paginator(posts,4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:

        posts = paginator.page(paginator.num_pages)    
    return render(request,'post_list.html',{'posts':posts, page:'pages', 'tag':tag})
    
    



class PostDetail(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "post_detail.html"

def post_detail(request, post):
    post=get_object_or_404(Post,slug=post,status='published')

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            return redirect(post.get_absolute_url()+'#'+str(new_comment.id))
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:6]
    
    return render(request, 'post_detail.html',{'post':post,'comments': comments,'comment_form':comment_form,'similar_posts':similar_posts})

templates/comment.html
{% extend base.html %}



<!-- Comments -->
<div>
    <h2 class="tm-color-primary tm-post-title">Comments</h2>
    <hr class="tm-hr-primary tm-mb-45" />
    <div class="tm-comment tm-mb-45">
      <figure class="tm-comment-figure">
        <!-- <img
          src="img/comment-1.jpg"
          alt="Image"
          class="mb-2 rounded-circle img-thumbnail"
        /> -->
        <figcaption class="tm-color-primary text-center">
          Mark Sonny
        </figcaption>
      </figure>
      <div>
        <p>
          Praesent aliquam ex vel lectus ornare tritique. Nunc et eros quis
          enim feugiat tincidunt et vitae dui. Nullam consectetur justo ac
          ex laoreet rhoncus. Nunc id leo pretium, faucibus sapien vel,
          euismod turpis.
        </p>
        <div class="d-flex justify-content-between">
          <a href="#" class="tm-color-primary">REPLY</a>
          <span class="tm-color-primary">June 14, 2020</span>
        </div>
      </div>
    </div>
    <div class="tm-comment-reply tm-mb-45">
      <hr />
      <div class="tm-comment">
        <figure class="tm-comment-figure">
          <img
            src="img/comment-2.jpg"
            alt="Image"
            class="mb-2 rounded-circle img-thumbnail"
          />
          <figcaption class="tm-color-primary text-center">
            Jewel Soft
          </figcaption>
        </figure>
        <p>
          Nunc et eros quis enim feugiat tincidunt et vitae dui. Nullam
          consectetur justo ac ex laoreet rhoncus. Nunc id leo pretium,
          faucibus sapien vel, euismod turpis.
        </p>
      </div>
      <span class="d-block text-right tm-color-primary">June 21, 2020</span>
    </div>
    <form action="" class="mb-5 tm-comment-form">
      <h2 class="tm-color-primary tm-post-title mb-4">Your comment</h2>
      <div class="mb-4">
        <input class="form-control" name="name" type="text" />
      </div>
      <div class="mb-4">
        <input class="form-control" name="email" type="text" />
      </div>
      <div class="mb-4">
        <textarea class="form-control" name="message" rows="6"></textarea>
      </div>
      <div class="text-right">
        <button class="tm-btn tm-btn-primary tm-btn-small">Submit</button>
      </div>
    </form>
  </div>

templates/pagination.html
{% if page.has_other_pages %}
  <ul class="pagination mt-3 mb-0">
    {% if page.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }}</span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

templates/post_detail.html
{% extends 'base.html' %}
{% load post_utils % }


{% block title %} - {{ post.title}} {% endblock title %}

{% block content %}

<div class="row tm-row">
  <div class="col-12">
    <hr class="tm-hr-primary tm-mb-55" />
    <img src="{{ post.image.url}}" class="rounded" alt="{{post.title}}" />
  </div>
</div>

<div class="row tm-row">

  <div class="col-lg-8 tm-post-col">
    <div class="tm-post-full" >
      <div class="mb-4">
        <h2 class="pt-2 tm-color-primary tm-post-title">{{ post.title }}</h2>
        <p class="tm-mb-40">{{ post.publish.date }} by {{ post.creator }}</p>
        <p class="tm-mb-40">{{ post.get_readtime }}</p>
        

        <p>
          {{ post.body|safe }}
        </p>
        <strong>Tags:</strong>
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_tag' tag.slug %}">
        <span class="d-block text-right tm-color-primary">{{tag.name}}</span>
        </a>
        {% endfor %}
      </div>

    </div>
  </div>
  
  <aside class="col-lg-4 tm-aside-col">
    <div class="tm-post-sidebar">
      <hr class="mb-3 tm-hr-primary" />
      <!-- <h2 class="mb-4 tm-post-title tm-color-primary">Categories</h2>
      <ul class="tm-mb-75 pl-5 tm-category-list">
        <li><a href="#" class="tm-color-primary">Visual Designs</a></li>
        <li><a href="#" class="tm-color-primary">Travel Events</a></li>
        <li><a href="#" class="tm-color-primary">Web Development</a></li>
        <li><a href="#" class="tm-color-primary">Video and Audio</a></li>
        <li><a href="#" class="tm-color-primary">Etiam auctor ac arcu</a></li>
        <li><a href="#" class="tm-color-primary">Sed im justo diam</a></li>
      </ul>
      <hr class="mb-3 tm-hr-primary" /> -->
      <h2 class="tm-mb-40 tm-post-title tm-color-primary">Related Posts({{similar_posts.count}})</h2>

      {% for post in similar_posts %}
      <a href="{{post.get_absolute_url}}" class="d-block tm-mb-40">
        <figure>
          <img src="{{post.image.url}}" alt="Image" class="mb-3 img-fluid" />
          <figcaption class="tm-color-primary">
            {{post.title}}
          </figcaption>
        </figure>
      </a>
      {% empty %}
      <p class="text-muted">There is no similar post yet</p>
      {% endfor %}
      
    </div>
  </aside>
</div>
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}

{% block content %}
{% if tag %}
        <h2 class="mb-3">Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

<div class="row tm-row">
    {% for post in posts %}
    <article class="col-12 col-md-6 tm-post">
        <hr class="tm-hr-primary">
        <a href="{{ post.get_absolute_url }}" class="effect-lily tm-post-link tm-pt-60">
            <div class="tm-post-link-inner">
                <img src="{{ post.image.url }}" alt="Image" class="img-fluid">                            
            </div>
            <span class="position-absolute tm-new-badge">New</span>
            <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{post.title}}</h2>
        </a>                    
        <p class="tm-pt-30">
            {{ post.body|safe|striptags|truncatechars:150 }}
        </p>
        <div class="d-flex justify-content-between tm-pt-45">
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_tag' tag.slug %}">
            <span class="tm-color-primary">{{tag.name}}</span>
            </a>
            {% endfor %}
            <span class="tm-color-primary">{{ post.publish.date }}</span>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <!-- <span>36 comments</span> -->
            <span>by {{ post.creator }}</span>
        </div>
    </article>
    {% endfor %}
     
</div>

{% include "pagination.html" with page=posts %}

{% endblock content %}